name: Daily action Test

on:
    schedule:
    - cron: "0 3 * * MON-FRI" # Runs at 03:00 UTC
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
          date > report.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated checkout workflow file"
          git push